<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'
import flatpickr from 'flatpickr'
import { Greek } from 'flatpickr/dist/l10n/gr.js'
import 'flatpickr/dist/flatpickr.min.css'

const props = defineProps<{
  modelValue: string
  minDate?: string
  maxDate?: string
  placeholder?: string
  id?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const inputRef = ref<HTMLInputElement | null>(null)
let flatpickrInstance: flatpickr.Instance | null = null

onMounted(() => {
  if (inputRef.value) {
    flatpickrInstance = flatpickr(inputRef.value, {
      locale: Greek,
      dateFormat: 'Y-m-d',
      altInput: true,
      altFormat: 'd F Y',
      minDate: props.minDate,
      maxDate: props.maxDate,
      defaultDate: props.modelValue || undefined,
      disableMobile: true,
      monthSelectorType: 'dropdown',
      animate: true,
      onChange: (_selectedDates, dateStr) => {
        emit('update:modelValue', dateStr)
      },
      onReady: (_selectedDates, _dateStr, instance) => {
        // Add custom class to the calendar for styling
        instance.calendarContainer?.classList.add('modern-flatpickr')
        // Force padding on the alternative input generated by flatpickr
        if (instance.altInput) {
          instance.altInput.style.setProperty('padding-left', '3.5rem', 'important')
          instance.altInput.classList.add('datepicker-input', 'input-elegant')
        }
      }
    })
  }
})

// Watch for external value changes
watch(() => props.modelValue, (newValue) => {
  if (flatpickrInstance && newValue !== flatpickrInstance.input.value) {
    flatpickrInstance.setDate(newValue, false)
  }
})

// Watch for min/max date changes
watch([() => props.minDate, () => props.maxDate], ([newMin, newMax]) => {
  if (flatpickrInstance) {
    flatpickrInstance.set('minDate', newMin)
    flatpickrInstance.set('maxDate', newMax)
  }
})

onBeforeUnmount(() => {
  if (flatpickrInstance) {
    flatpickrInstance.destroy()
  }
})
</script>

<template>
  <div class="datepicker-wrapper">
    <div class="datepicker-icon">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
    </div>
    <input
      ref="inputRef"
      :id="id"
      type="text"
      :placeholder="placeholder || 'Επιλέξτε ημερομηνία'"
      class="datepicker-input input-elegant"
      style="padding-left: 3.5rem !important;"
      readonly
    />
  </div>
</template>

<style scoped>
.datepicker-wrapper {
  position: relative;
}

.datepicker-icon {
  position: absolute;
  left: 12px;
  top: 50%;
  transform: translateY(-50%);
  color: var(--marble-400);
  pointer-events: none;
  z-index: 1;
}

.datepicker-input,
.datepicker-wrapper input {
  padding-left: 3.5rem !important;
  cursor: pointer;
}

.datepicker-input:focus {
  cursor: text;
}
</style>


